### PR TITLE
support locally installed esformatter

### PR DESCRIPTION
**Pull request by felixhao28**

### CODE REVIEW

**Comment by felixhao28** [comment]
I (and I believe many other people) install esformatter as a local dev-dependency (it is easier for team collaboration). With this PR, sublime-esformatter will first search for locally installed esformatter and then global one.

**Comment by felixhao28** [comment]
Just found someone with the same issue: #64

**Comment by piuccio** [comment]
looks nice, just out of curiosity, are you using mac / win / linux?

**Comment by felixhao28** [comment]
Windows. And all my colleagues use win too so I only tested it on windows.

**Comment by piuccio** [comment]
great I can test on mac

**Comment by piuccio** [comment]
@felixhao28 thanks for this and sorry if it took so long. I tested on mac and works fine.

**Pull request merged**
